=== fabe85/Alevin2/bin/XML/Alevin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://sourceforge.net/projects/alevin/"
    xmlns:Alevin="http://sourceforge.net/projects/alevin/"
    targetNamespace="http://sourceforge.net/projects/alevin/"
    elementFormDefault="qualified"
>

 <xsd:element name="MappingTest" type="MappingTestType" />

  
  <xsd:complexType name="MappingTestType">
    <xsd:sequence>
      <xsd:element name="TestGenerator" minOccurs="1" maxOccurs="1">
        <xsd:complexType>
          <xsd:attribute name="className" type="xsd:string" />
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="ScenarioResult" type="ScenarioType" minOccurs="0" maxOccurs="unbounded" >
        <xsd:unique name="UniqeParam">
					<xsd:selector xpath="./Alevin:ScenarioParameter" /> 
					<xsd:field xpath="@name" /> 
				</xsd:unique>
        <xsd:unique name="UniqeMetric">
					<xsd:selector xpath="./Alevin:ScenarioMetric" /> 
					<xsd:field xpath="@name" /> 
				</xsd:unique>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required" />
  </xsd:complexType>
  

  
	<xsd:complexType name="ScenarioType">
		<xsd:sequence>
			<xsd:element name="ScenarioParameter" type="ScenarioParameterType" minOccurs="1" maxOccurs="unbounded" />
			<xsd:element name="ScenarioMetric" type="ScenarioMetricType" minOccurs="1" maxOccurs="unbounded" />
			<xsd:element name="ScenarioNetworks" type="NetworkType" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
    
  
  
	<xsd:complexType name="ScenarioParameterType">
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="value" type="xsd:string" use="required" />
	</xsd:complexType>
  
  <xsd:complexType name="ScenarioMetricType">
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="result" type="xsd:string" use="required" />
  </xsd:complexType>


<!--
The following elements are converted and adapted scenario.dtd 
-->

  <xsd:complexType name="NetworkType">
   <xsd:sequence>
    <xsd:element ref='SubstrateNetwork'/>
    <xsd:element ref='VirtualNetworks'/>
   </xsd:sequence>
  </xsd:complexType>

  <xsd:element name='Scenario'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='SubstrateNetwork'/>
    <xsd:element ref='VirtualNetworks'/>
   </xsd:sequence>
  </xsd:complexType>
  </xsd:element>

 <xsd:element name='SubstrateNetwork'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='SubstrateNodes'/>
    <xsd:element ref='SubstrateLinks'/>
   </xsd:sequence>
  </xsd:complexType>
  </xsd:element>

 <xsd:element name='SubstrateNodes'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='SubstrateNode' maxOccurs='unbounded'/>
   </xsd:sequence>
  </xsd:complexType>
  </xsd:element>

 <xsd:element name='SubstrateLinks'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='SubstrateLink' maxOccurs='unbounded'/>
   </xsd:sequence>
  </xsd:complexType>
  </xsd:element>

 <xsd:element name='SubstrateNode'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='Resource' maxOccurs='unbounded'/>
   </xsd:sequence>
   <xsd:attribute name='id' type='xsd:string' use='required'/>
   <xsd:attribute name='coordinateX' type='xsd:string' use='required'/>
   <xsd:attribute name='coordinateY' type='xsd:string' use='required'/>
  </xsd:complexType>
  </xsd:element>

 <xsd:element name='SubstrateLink'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='Resource' maxOccurs='unbounded'/>
   </xsd:sequence>
   <xsd:attribute name='id' type='xsd:string' use='required'/>
   <xsd:attribute name='source' type='xsd:string' use='required'/>
   <xsd:attribute name='destination' type='xsd:string' use='required'/>
  </xsd:complexType>
  </xsd:element>

 <xsd:element name='Resource'>
  <xsd:complexType>
   <xsd:sequence>
   	<xsd:element name="ConstructParameter" type="ParameterType" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element name='Parameter' type="ParameterType" minOccurs="0" maxOccurs='unbounded'/>
   </xsd:sequence>
   <xsd:attribute name='type' type='xsd:string' use='required'/>
  </xsd:complexType>
  </xsd:element>

 <xsd:element name='VirtualNetworks'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='VirtualNetwork' maxOccurs='unbounded'/>
   </xsd:sequence>
  </xsd:complexType>
  </xsd:element>

 <xsd:element name='VirtualNetwork'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='VirtualNodes'/>
    <xsd:element ref='VirtualLinks'/>
   </xsd:sequence>
   <xsd:attribute name='layer' type='xsd:string' use='required'/>
  </xsd:complexType>
  </xsd:element>

 <xsd:element name='VirtualNodes'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='VirtualNode' maxOccurs='unbounded'/>
   </xsd:sequence>
  </xsd:complexType>
  </xsd:element>

 <xsd:element name='VirtualLinks'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='VirtualLink' maxOccurs='unbounded'/>
   </xsd:sequence>
  </xsd:complexType>
  </xsd:element>

 <xsd:element name='VirtualNode'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='Demand' maxOccurs='unbounded'/>
   </xsd:sequence>
   <xsd:attribute name='id' type='xsd:string' use='required'/>
   <xsd:attribute name='coordinateX' type='xsd:string' use='required'/>
   <xsd:attribute name='coordinateY' type='xsd:string' use='required'/>
  </xsd:complexType>
  </xsd:element>

 <xsd:element name='VirtualLink'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='Demand' maxOccurs='unbounded'/>
    <xsd:element ref='HiddenHopDemand' minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>
   <xsd:attribute name='id' type='xsd:string' use='required'/>
   <xsd:attribute name='source' type='xsd:string' use='required'/>
   <xsd:attribute name='destination' type='xsd:string' use='required'/>
  </xsd:complexType>
  </xsd:element>

 <xsd:element name='Demand'>
  <xsd:complexType>
   <xsd:sequence>
   	<xsd:element name="ConstructParameter" type="ParameterType" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element name='Parameter' type="ParameterType" minOccurs="0" maxOccurs='unbounded'/>
    <xsd:element ref='Mapping' minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>
   <xsd:attribute name='type' type='xsd:string' use='required'/>
  </xsd:complexType>
  </xsd:element>

 <xsd:element name='HiddenHopDemand'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="Parameter" type='ParameterType' maxOccurs='unbounded'/>
    <xsd:element ref='Mapping' minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>
   <xsd:attribute name='type' type='xsd:string' use='required'/>
  </xsd:complexType>
  </xsd:element>

 	


  <xsd:complexType name="ParameterType">
   <xsd:attribute name='name' type='xsd:string' use='required'/>
   <xsd:attribute name='type' use='required'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='Integer'/>
      <xsd:enumeration value='String'/>
      <xsd:enumeration value='Double'/>
      <xsd:enumeration value='Boolean'/>
      <xsd:enumeration value="localSNet"/>
      <xsd:enumeration value="Collection_String"/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
   <xsd:attribute name='value' type='xsd:string' use='required'/>
  </xsd:complexType>

 <xsd:element name='Mapping'>
  <xsd:complexType>
   <xsd:attribute name='substrateEntity' type='xsd:string' use='required'/>
   <xsd:attribute name='resourceType' type='xsd:string' use='required'/>
  </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== fabe85/Alevin2/src/XML/Example1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Scenario 
  xsi:schemaLocation="http://sourceforge.net/projects/alevin/ ./Alevin.xsd" 
  xmlns="http://sourceforge.net/projects/alevin/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
  <SubstrateNetwork>
    <SubstrateNodes>
      <SubstrateNode coordinateX="-4.803" coordinateY="-2.969" id="1">
        <Resource type="IdResource">
          <Parameter name="Id" type="String" value="1"/>
        </Resource>
        <Resource type="CpuResource">
          <Parameter name="Cycles" type="Double" value="100"/>
        </Resource>
      </SubstrateNode>
      <SubstrateNode coordinateX="2.548" coordinateY="-6.104" id="2">
        <Resource type="IdResource">
          <Parameter name="Id" type="String" value="2"/>
        </Resource>
        <Resource type="CpuResource">
          <Parameter name="Cycles" type="Double" value="100"/>
        </Resource>
      </SubstrateNode>
      <SubstrateNode coordinateX="2.062" coordinateY="1.734" id="3">
        <Resource type="IdResource">
          <Parameter name="Id" type="String" value="3"/>
        </Resource>
        <Resource type="CpuResource">
          <Parameter name="Cycles" type="Double" value="100"/>
        </Resource>
      </SubstrateNode>
      <SubstrateNode coordinateX="-4.046" coordinateY="3.085" id="4">
        <Resource type="IdResource">
          <Parameter name="Id" type="String" value="4"/>
        </Resource>
      </SubstrateNode>
    </SubstrateNodes>
    <SubstrateLinks>
      <SubstrateLink destination="2" id="6" source="1">
        <Resource type="BandwidthResource">
          <Parameter name="Bandwidth" type="Double" value="50"/>
        </Resource>
      </SubstrateLink>
      <SubstrateLink destination="1" id="7" source="3">
        <Resource type="BandwidthResource">
          <Parameter name="Bandwidth" type="Double" value="50"/>
        </Resource>
      </SubstrateLink>
      <SubstrateLink destination="3" id="8" source="2">
        <Resource type="BandwidthResource">
          <Parameter name="Bandwidth" type="Double" value="70"/>
        </Resource>
      </SubstrateLink>
      <SubstrateLink destination="4" id="9" source="1">
        <Resource type="BandwidthResource">
          <Parameter name="Bandwidth" type="Double" value="40"/>
        </Resource>
      </SubstrateLink>
      <SubstrateLink destination="3" id="10" source="4">
        <Resource type="BandwidthResource">
          <Parameter name="Bandwidth" type="Double" value="70"/>
        </Resource>
      </SubstrateLink>
    </SubstrateLinks>
  </SubstrateNetwork>
  <VirtualNetworks>
    <VirtualNetwork layer="1">
      <VirtualNodes>
        <VirtualNode coordinateX="-0.757" coordinateY="-3.622" id="11">
          <Demand type="IdDemand">
            <Parameter name="DemandedId" type="String" value="1"/>
          </Demand>
          <Demand type="CpuDemand">
            <Parameter name="DemandedCycles" type="Double" value="50"/>
          </Demand>
        </VirtualNode>
        <VirtualNode coordinateX="4.216" coordinateY="-0.595" id="12">
          <Demand type="IdDemand">
            <Parameter name="DemandedId" type="String" value="2"/>
          </Demand>
          <Demand type="CpuDemand">
            <Parameter name="DemandedCycles" type="Double" value="100"/>
          </Demand>
        </VirtualNode>
        <VirtualNode coordinateX="-4.541" coordinateY="1.081" id="13">
          <Demand type="IdDemand">
            <Parameter name="DemandedId" type="String" value="3"/>
          </Demand>
          <Demand type="CpuDemand">
            <Parameter name="DemandedCycles" type="Double" value="35"/>
          </Demand>
        </VirtualNode>
      </VirtualNodes>
      <VirtualLinks>
        <VirtualLink destination="13" id="14" source="11">
          <Demand type="BandwidthDemand">
            <Parameter name="DemandedBandwidth" type="Double" value="25"/>
          </Demand>
        </VirtualLink>
        <VirtualLink destination="13" id="15" source="12">
          <Demand type="BandwidthDemand">
            <Parameter name="DemandedBandwidth" type="Double" value="30"/>
          </Demand>
        </VirtualLink>
      </VirtualLinks>
    </VirtualNetwork>
  </VirtualNetworks>
</Scenario>

=== fabe85/Alevin2/bin/XML/DisconnectedVN.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Scenario 
  xsi:schemaLocation="http://sourceforge.net/projects/alevin/ ./Alevin.xsd" 
  xmlns="http://sourceforge.net/projects/alevin/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
  <SubstrateNetwork>
    <SubstrateNodes>
      <SubstrateNode coordinateX="-5.948" coordinateY="-8.276" id="0">
        <Resource type="CpuResource">
          <Parameter name="Cycles" type="Double" value="5.0"/>
        </Resource>
      </SubstrateNode>
      <SubstrateNode coordinateX="-1.552" coordinateY="-8.276" id="1">
        <Resource type="CpuResource">
          <Parameter name="Cycles" type="Double" value="5.0"/>
        </Resource>
      </SubstrateNode>
      <SubstrateNode coordinateX="-5.776" coordinateY="-2.5" id="2">
        <Resource type="CpuResource">
          <Parameter name="Cycles" type="Double" value="5.0"/>
        </Resource>
      </SubstrateNode>
      <SubstrateNode coordinateX="-1.379" coordinateY="-2.758" id="3">
        <Resource type="CpuResource">
          <Parameter name="Cycles" type="Double" value="5.0"/>
        </Resource>
      </SubstrateNode>
    </SubstrateNodes>
    <SubstrateLinks>
      <SubstrateLink destination="1" id="4" source="0">
        <Resource type="BandwidthResource">
          <Parameter name="Bandwidth" type="Double" value="5.0"/>
        </Resource>
      </SubstrateLink>
      <SubstrateLink destination="2" id="5" source="0">
        <Resource type="BandwidthResource">
          <Parameter name="Bandwidth" type="Double" value="5.0"/>
        </Resource>
      </SubstrateLink>
      <SubstrateLink destination="1" id="6" source="3">
        <Resource type="BandwidthResource">
          <Parameter name="Bandwidth" type="Double" value="5.0"/>
        </Resource>
      </SubstrateLink>
    </SubstrateLinks>
  </SubstrateNetwork>
  <VirtualNetworks>
    <VirtualNetwork layer="1">
      <VirtualNodes>
        <VirtualNode coordinateX="-6.638" coordinateY="-8.793" id="7">
          <Demand type="CpuDemand">
            <Parameter name="DemandedCycles" type="Double" value="5.0"/>
          </Demand>
        </VirtualNode>
        <VirtualNode coordinateX="-2.845" coordinateY="-8.793" id="8">
          <Demand type="CpuDemand">
            <Parameter name="DemandedCycles" type="Double" value="5.0"/>
          </Demand>
        </VirtualNode>
        <VirtualNode coordinateX="-6.724" coordinateY="-4.741" id="9">
          <Demand type="CpuDemand">
            <Parameter name="DemandedCycles" type="Double" value="5.0"/>
          </Demand>
        </VirtualNode>
        <VirtualNode coordinateX="-2.672" coordinateY="-4.396" id="12">
          <Demand type="CpuDemand">
            <Parameter name="DemandedCycles" type="Double" value="5.0"/>
          </Demand>
        </VirtualNode>
      </VirtualNodes>
      <VirtualLinks>
        <VirtualLink destination="9" id="10" source="7">
          <Demand type="BandwidthDemand">
            <Parameter name="DemandedBandwidth" type="Double" value="5.0"/>
          </Demand>
        </VirtualLink>
        <VirtualLink destination="8" id="11" source="7">
          <Demand type="BandwidthDemand">
            <Parameter name="DemandedBandwidth" type="Double" value="5.0"/>
          </Demand>
        </VirtualLink>
      </VirtualLinks>
    </VirtualNetwork>
  </VirtualNetworks>
</Scenario>

=== fabe85/Alevin2/bin/XML/Test_gen.xml
<?xml version="1.0" encoding="UTF-8"?>
<MappingTest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://sourceforge.net/projects/alevin/ ./Alevin.xsd" xmlns="http://sourceforge.net/projects/alevin/" name="Test">
  <TestGenerator className="tests.scenarios.mls.MLSTestGenerator"/>
  <ScenarioResult>
    <ScenarioParameter name="Waxman_alpha" value="0.5"/>
    <ScenarioParameter name="Waxman_beta" value="0.5"/>
    <ScenarioParameter name="NumVNodes" value="10.0"/>
    <ScenarioParameter name="NumVNets" value="5.0"/>
    <ScenarioParameter name="SNetSize" value="100.0"/>
    <ScenarioParameter name="MLS_Theta" value="1.0"/>
    <ScenarioParameter name="MLS_SecLevels" value="5.0"/>
    <ScenarioParameter name="MLS_NumCategories" value="2.0"/>
  </ScenarioResult>
  <ScenarioResult>
    <ScenarioParameter name="Waxman_alpha" value="0.5"/>
    <ScenarioParameter name="Waxman_beta" value="0.5"/>
    <ScenarioParameter name="NumVNodes" value="10.0"/>
    <ScenarioParameter name="NumVNets" value="5.0"/>
    <ScenarioParameter name="SNetSize" value="100.0"/>
    <ScenarioParameter name="MLS_Theta" value="1.0"/>
    <ScenarioParameter name="MLS_SecLevels" value="5.0"/>
    <ScenarioParameter name="MLS_NumCategories" value="6.0"/>
  </ScenarioResult>
  <ScenarioResult>
    <ScenarioParameter name="Waxman_alpha" value="0.5"/>
    <ScenarioParameter name="Waxman_beta" value="0.5"/>
    <ScenarioParameter name="NumVNodes" value="10.0"/>
    <ScenarioParameter name="NumVNets" value="5.0"/>
    <ScenarioParameter name="SNetSize" value="100.0"/>
    <ScenarioParameter name="MLS_Theta" value="1.0"/>
    <ScenarioParameter name="MLS_SecLevels" value="17.0"/>
    <ScenarioParameter name="MLS_NumCategories" value="2.0"/>
  </ScenarioResult>
  <ScenarioResult>
    <ScenarioParameter name="Waxman_alpha" value="0.5"/>
    <ScenarioParameter name="Waxman_beta" value="0.5"/>
    <ScenarioParameter name="NumVNodes" value="10.0"/>
    <ScenarioParameter name="NumVNets" value="5.0"/>
    <ScenarioParameter name="SNetSize" value="100.0"/>
    <ScenarioParameter name="MLS_Theta" value="2.0"/>
    <ScenarioParameter name="MLS_SecLevels" value="5.0"/>
    <ScenarioParameter name="MLS_NumCategories" value="2.0"/>
  </ScenarioResult>
  <ScenarioResult>
    <ScenarioParameter name="Waxman_alpha" value="0.5"/>
    <ScenarioParameter name="Waxman_beta" value="0.5"/>
    <ScenarioParameter name="NumVNodes" value="10.0"/>
    <ScenarioParameter name="NumVNets" value="5.0"/>
    <ScenarioParameter name="SNetSize" value="100.0"/>
    <ScenarioParameter name="MLS_Theta" value="2.0"/>
    <ScenarioParameter name="MLS_SecLevels" value="5.0"/>
    <ScenarioParameter name="MLS_NumCategories" value="6.0"/>
  </ScenarioResult>
  <ScenarioResult>
    <ScenarioParameter name="Waxman_alpha" value="0.5"/>
    <ScenarioParameter name="Waxman_beta" value="0.5"/>
    <ScenarioParameter name="NumVNodes" value="10.0"/>
    <ScenarioParameter name="NumVNets" value="5.0"/>
    <ScenarioParameter name="SNetSize" value="100.0"/>
    <ScenarioParameter name="MLS_Theta" value="2.0"/>
    <ScenarioParameter name="MLS_SecLevels" value="17.0"/>
    <ScenarioParameter name="MLS_NumCategories" value="2.0"/>
  </ScenarioResult>
  <ScenarioResult>
    <ScenarioParameter name="Waxman_alpha" value="0.5"/>
    <ScenarioParameter name="Waxman_beta" value="0.5"/>
    <ScenarioParameter name="NumVNodes" value="10.0"/>
    <ScenarioParameter name="NumVNets" value="5.0"/>
    <ScenarioParameter name="SNetSize" value="100.0"/>
    <ScenarioParameter name="MLS_Theta" value="3.0"/>
    <ScenarioParameter name="MLS_SecLevels" value="5.0"/>
    <ScenarioParameter name="MLS_NumCategories" value="2.0"/>
  </ScenarioResult>
  <ScenarioResult>
    <ScenarioParameter name="Waxman_alpha" value="0.5"/>
    <ScenarioParameter name="Waxman_beta" value="0.5"/>
    <ScenarioParameter name="NumVNodes" value="10.0"/>
    <ScenarioParameter name="NumVNets" value="5.0"/>
    <ScenarioParameter name="SNetSize" value="100.0"/>
    <ScenarioParameter name="MLS_Theta" value="3.0"/>
    <ScenarioParameter name="MLS_SecLevels" value="5.0"/>
    <ScenarioParameter name="MLS_NumCategories" value="6.0"/>
  </ScenarioResult>
  <ScenarioResult>
    <ScenarioParameter name="Waxman_alpha" value="0.5"/>
    <ScenarioParameter name="Waxman_beta" value="0.5"/>
    <ScenarioParameter name="NumVNodes" value="10.0"/>
    <ScenarioParameter name="NumVNets" value="5.0"/>
    <ScenarioParameter name="SNetSize" value="100.0"/>
    <ScenarioParameter name="MLS_Theta" value="3.0"/>
    <ScenarioParameter name="MLS_SecLevels" value="17.0"/>
    <ScenarioParameter name="MLS_NumCategories" value="2.0"/>
  </ScenarioResult>
</MappingTest>
